spring.application.name=http-interface

server.servlet.context-path=/simulator
server.port=8010

simulator.base-url=http://10.131.17.197:8010/simulator

# LOG
log.max.file.size=3MB
log.total.size=50GB
log.max.history=100
log.folder=log/
